version: '3.8'

services:
  cartserviceapi:
    image: ${DOCKER_REGISTRY-}cartserviceapi
    build:
      context: .
      dockerfile: CartServiceApi/Dockerfile
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DATABASE_CONNECTION_STRING=Host=database-1.cpukomqyes2t.us-east-1.rds.amazonaws.com;Database=postgres;Username=postgres;Password=ENWwRKuZXd9iV1EpcJzH;Port=5432;SSL Mode=Require;Trust Server Certificate=true;
    networks:
      - backend

networks:
  backend:
    driver: bridge
